### ISSUE TITLE
Google Functions support

### ISSUE THREAD

**Issue by yaman** [seek-oss/serverless-haskell#107]
Thanks for the great library. I am looking a way to run serverless-haskell in Google Functions instead of AWS Lambda. 

Aws Lambda with custom runtime support makes it pretty easy to create runtimes aside with officially supported languages. Google Functions doen't have custom runtimes support and I am trying to figure out if running haskell is even possible.

Do you have any idea on how to achieve this?

**Comment by koterpillar** [comment]
We're currently using a JavaScript wrapper to launch a Haskell process, as this project started before AWS provided the ability to BYO runtimes. This should be easy to extend to Google Functions - see https://github.com/seek-oss/serverless-haskell/blob/master/serverless-plugin/handler.template.js for the current AWS interface.

**Comment by yaman** [comment]
@koterpillar as you said, I verify that it works with a simple wrapper at Google Functions.
