### ISSUE TITLE
Node 10.x missing library error

### ISSUE THREAD

**Issue by tjmcewan** [seek-oss/serverless-haskell#108]
Howdy, when we try to run using the selected 10.x runtime, our lambda times out and we get this error:

```
error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

Changing the runtime manually back to 8.10 allows the function to run.

**Comment by koterpillar** [comment]
Here's what I found:

Amazon claims the Lambda environment for Node.js 10 is Amazon Linux 2: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Serverless-haskell used an older Amazon Linux image to dump the available libraries, see https://github.com/seek-oss/serverless-haskell/blob/master/serverless-plugin/update_aws_libraries.js.

There is no official Docker image of Amazon Linux 2 with the same version as the Lambda runtime claims to have: https://hub.docker.com/_/amazonlinux/?tab=tags

However, there are also reports that it is different (missing libraries): https://forums.aws.amazon.com/message.jspa?messageID=901906

Might need to look at https://github.com/lambci/docker-lambda/ to make a new list.
