### ISSUE TITLE
Google run

### ISSUE THREAD

**Issue by janat08** [seek-oss/serverless-haskell#127]
I belief you intend to Port this to Google, but they released cloud run which is serverless on containers. Between that and anthos, will delivering Google offering become priority.

Im not in love with aws, because of the above, aws doesnt deserve it :p.

**Comment by janat08** [comment]
There's already experimental package for cloud run, FYI.

**Comment by koterpillar** [comment]
Hello and thank you for raising this!

I don't have access to a Google Cloud account since we're using AWS everywhere. However, if you're interested in adding support, it would be welcome!
