### ISSUE TITLE
Avoid Docker / NodeJS runtime wrapper?

### ISSUE THREAD

**Issue by danwdart** [seek-oss/serverless-haskell#155]
As specified in https://www.haskelltutorials.com/haskell-aws-lambda/avoid-serverless-haskell.html, AWS supports anything - doesn't necessarily have to have Node in the middle. Maybe this library can jump around the Node & the Docker stuff.

**Comment by koterpillar** [comment]
The wrapper isn't used anymore [since 0.11.0](https://github.com/seek-oss/serverless-haskell/blob/master/ChangeLog.md#0110).

Docker is, however, still used to build the binary for the architecture of AWS Lambda (Linux, x64, right glibc) no matter what your machine is.

**Comment by danwdart** [comment]
Yeah, fpco/stack-build:lts-13.30 - gotcha - was just wondering if there was a smaller Docker image we could put the libc from into the zip and use the bootstrap on.. if I've already built the binaries on my local machine.

**Comment by koterpillar** [comment]
Libc isn't going into the zip, just your other dependencies. It just can't be newer than on AWS. Actually I'm curious to see how Rust, etc. are solving this.

**Comment by danwdart** [comment]
Hmm, yes. I noticed that it's just old on AWS's side but wonder if all environments are as old.
