### ISSUE TITLE
Stack template

### ISSUE THREAD

**Issue by koterpillar** [seek-oss/serverless-haskell#25]
`stack new serverless-haskell` should produce a project ready to be deployed. Note: no new Stack templates are currently accepted pending a refactor.

**Comment by Tehnix** [comment]
You might be interested in the update on `stack new` working on URLs https://github.com/commercialhaskell/stack/issues/2681#issuecomment-388639518.

This means you could make a `.hsfiles` template in this repo and then point to that. I just tested it out on the [simple](https://github.com/commercialhaskell/stack-templates/blob/master/simple.hsfiles) template, 

```
stack new TestServ https://raw.githubusercontent.com/commercialhaskell/stack-templates/master/simple.hsfiles
```

which works like one would expect.

**Comment by koterpillar** [comment]
Looks like `github:serverless-haskell/aws` should work _if_ we make this repo its separate organisation.

**Comment by koterpillar** [comment]
This is done in #78.
