### ISSUE TITLE
Fails to build on LTS 11 (was: instructions in readme result in error)

### ISSUE THREAD

**Issue by silky** [seek-oss/serverless-haskell#34]
i am trying to use this, and when i run `sls deploy` i get:

```
04:27 PM noon ∈ lf-test-hs ♫ sls deploy
Serverless: Package version mismatch: NPM: 0.4.2, Stack: undefined. Versions must be in sync to work correctly.
 
  Error --------------------------------------------------
 
  Package version mismatch.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           9.9.0
     Serverless Version:     1.26.1
 
```

taking a look at the code, it seems the problem is that i do not have `serverless-haskell` as a dependency:

```
04:29 PM noon ∈ lf-test-hs ♫ stack ls dependencies --depth 1
aeson 1.2.4.0
base 4.10.1.0
lf-test-hs 0.1.0.0
```

i'm using `lts-11.2`. 

i also can't actually find a build configuration in the `stack.yaml` that lets me actually _build_ `serverless-haskell`.

i tried `allow-newer: true` and even that failed with some build error way down the line.

:(

**Comment by koterpillar** [comment]
If you don't have `serverless-haskell` as a dependency, are you using `AWSLambda` at all in your code? You will need it to process the messages sent from AWS Lambda.

I remember saying somewhere that LTS 9 and 10 are supported, I'll try to add 11 and see if that brings new problems.

**Comment by silky** [comment]
true true ...

turns out i had accidentally named my main `Main.js` instead of `Main.hs`, which is why it compiled fine ... :)

i'm rebuilding with lts-10.1 now.

**Comment by silky** [comment]
cool, well i can get it to build with 10.1

i'll happily close this issue, but it would be nice it the readme could be followed step-by-step, rather than having to think too much :)

**Comment by koterpillar** [comment]
Looks like LTS 11 dropped amazonka (because of one of its deps?), you aren't going to get very far without it.

**Comment by koterpillar** [comment]
Ah, here it is: https://github.com/brendanhay/amazonka/pull/454

**Comment by koterpillar** [comment]
Will re-open for visibility.

**Comment by colehaus** [comment]
FYI, the right `extra-deps` declaration in `stack.yaml` fixes this. e.g.

```
extra-deps:
  - serverless-haskell-0.4.2
  - amazonka-core-1.5.0
  - amazonka-kinesis-1.5.0
  - amazonka-s3-1.5.0
  - conduit-1.2.13.1
  - conduit-extra-1.2.3.2
  - resourcet-1.1.11
  - xml-conduit-1.7.1.1
```
