### ISSUE TITLE
Support deployment of projects located in sub-directories

### ISSUE THREAD

**Issue by justinpastoncooper** [seek-oss/serverless-haskell#39]
serverless-haskell currently expects the stack project to be located at the same level as serverless.yml. A `handler` of the form `src1/src2/packagename.handlername` is not supported.

I have made a fix for this which supports both the case where the stack project is at the same level, and the case where it isn't. I can make a pull request for this if desired.

**Comment by koterpillar** [comment]
Should be good, you're welcome to make the PR!
