### ISSUE TITLE
Document which ghc version is being used in the README

### ISSUE THREAD

**Issue by alexanderkjeldaas** [seek-oss/serverless-haskell#4]
The readme is good, but it doesn't explain what happens during `deploy`.  Which ghc version is being used?  Is ghci used?  Which build systems are used?  Cabal or stack?

**Comment by koterpillar** [comment]
Hi, can you please check the updated README in #7 (https://github.com/seek-oss/serverless-haskell/blob/update-docs/README.md) and tell if it addresses your question?

**Comment by alexanderkjeldaas** [comment]
lgtm!
