### ISSUE TITLE
Support binary dependencies

### ISSUE THREAD

**Issue by justinpastoncooper** [seek-oss/serverless-haskell#42]
Binary dependencies should be listed in `custom.haskell.binaryDependencies` and packaged along with the executables. The library dependencies of each binary dependency would also be packaged.

I'm working on a fix which would put the binaries in a sub-directory. This sub-directory would be added to PATH, after which the executable would be executed. Do you think this is a good solution?

**Comment by justinpastoncooper** [comment]
custom.haskell.binaryDependencies could be a map from function name to a list of its dependencies in case multiple functions are defined.

**Comment by koterpillar** [comment]
Serverless will include any files in the current directory in the package by default. Including their dependencies is a valid use case but I don't see how it's related to Haskell.

**Comment by justinpastoncooper** [comment]
My example is that I have a project which requires the `Gnuplot` Haskell package. This package expects `gnuplot` to be on the path. As far as I understand, having `gnuplot` in the same directory as the executable would not solve this. Even if it did, who is to handle the library dependencies of `gnuplot`?

**Comment by justinpastoncooper** [comment]
So I've come up with a "solution", but there seem to be a lot of library versioning issues, which don't see resolvable. I've decided that it might make more sense to simply build dependencies on Amazon's docker image and package them that way.

**Comment by koterpillar** [comment]
OK, I understand your use case but it's not related to running Haskell. Feel free to pull the library resolution code from here if you find it useful though!
