### ISSUE TITLE
[Feature] Consider adding support for serverless-offline

### ISSUE THREAD

**Issue by otbe** [seek-oss/serverless-haskell#48]
Hi,

I wonder if it would be possible to add support for [serverless-offline](https://github.com/dherault/serverless-offline). It would be awesome to be able to develop a haskell lambda locally with all the available plugins. :)

Whats your opinion?

Thanks!

**Comment by koterpillar** [comment]
Some sort of local running mode would certainly be good. Another avenue for this was hiding API Gateway behind a wai-compatible layer, and doing the local development using the regular wai server.

**Comment by koterpillar** [comment]
It seems that serverless-offline doesn't pass in `context.protocol` as specified in https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html. From a quick glance, one can add that field in https://github.com/dherault/serverless-offline/blob/master/src/createLambdaProxyContext.js.

**Comment by otbe** [comment]
I opened an issue in serverless-offline for the protocol part. 
Now Im getting 
```
Serverless: GET /hello/world (λ: apigw)
This should go to logs
{"body":"{\"name\":\"Hello, world\"}","headers":{},"statusCode":200}
child process output bad JSON:
Serverless: Failure: child process output bad JSON:
Serverless: Replying 200
```
From a small debugging session its seems to me that [output](https://github.com/seek-oss/serverless-haskell/blob/master/serverless-plugin/handler.template.js#L32) is just an empty string when parsing.

**Comment by koterpillar** [comment]
OK, it would actually work if you set `AWS_LAMBDA_FUNCTION_NAME`. I'm looking into how to make that check better.
