### ISSUE TITLE
Document which serverless cloud providers are supported

### ISSUE THREAD

**Issue by alexanderkjeldaas** [seek-oss/serverless-haskell#5]
It would be good to document whether this project is restricted to aws lambda or if all serverless cloud providers are supported (and which ones are tested).

**Comment by koterpillar** [comment]
Hi, can you please check the updated README in #7 (https://github.com/seek-oss/serverless-haskell/blob/update-docs/README.md) and tell if it addresses your question?

**Comment by alexanderkjeldaas** [comment]
Very good, but it doesn't say *what* makes this AWS Lambda-specific.  The code in https://hackage.haskell.org/package/serverless-haskell-0.0.6/docs/AWSLambda-Handler.html looks very generic.  I understand that the Events are Lambda-specific, but since serveless is cloud-agnostic, a sentence on what makes it Lambda-specific would be great.

**Comment by koterpillar** [comment]
Added a note. Leave a comment if you think it's still unclear.
