### ISSUE TITLE
glibc 2.27 missing if built on Ubuntu 18.04

### ISSUE THREAD

**Issue by NickSeagull** [seek-oss/serverless-haskell#53]
I'm trying to deploy the example project, but it fails given that Ubuntu 18.04 is shipped with `glibc` 2.27, so when invoking the lambda it complains that it cannot find it.

Any ideas on how to fix this? Is there a docker image available for building this properly?

**Comment by koterpillar** [comment]
Please try building with `docker: true`. Looks like we need to make that the default even on Linux, to avoid this kind of compatibility problems.

**Comment by NickSeagull** [comment]
That worked, thanks!!
