### ISSUE TITLE
`sls deploy` fails with no error message when building with static linking

### ISSUE THREAD

**Issue by JBetz** [seek-oss/serverless-haskell#56]
After adding `ld-options: -static -pthread` to my .cabal, `sls deploy` fails in the stack build step with no error message. During the build, stack issues a bunch of warnings like `Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking"`, but no actual error messages. Yet for whatever reason the process returns status code 1.

Odder still, when I change the fail condition in the [runStack](https://github.com/seek-oss/serverless-haskell/blob/d5af1e88e3d2809d924e5571066c51fffd80c0f1/serverless-plugin/index.js#L75) function from `result.status > 0` to `result.status > 1`, the executable gets deployed and runs successfully. 

Considering that static linking is often necessary for deployment to serverless, there should be some better handling for this case, and we should also look upstream to figure out why stack is returning an error code.

**Comment by koterpillar** [comment]
I'm curious, do you have a case where the default linking doesn't work? The plugin packages up all of your library dependencies together with the executable, so it should be fine.

Does `stack build` with the same arguments fail (exit code > 0) when invoked directly? If so, that might need to be reported to Stack.

**Comment by JBetz** [comment]
> I'm curious, do you have a case where the default linking doesn't work? The plugin packages up all of your library dependencies together with the executable, so it should be fine.

The executable was failing on lambda with: `./exe: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./exe)`

> Does stack build with the same arguments fail (exit code > 0) when invoked directly? If so, that might need to be reported to Stack.

No, it succeeds. But after adding some logs to the `runStack` function, I've narrowed it down to a [different stack call](https://github.com/seek-oss/serverless-haskell/blob/53abbf7e06ba28d291b5be84085fb5b6ac35ca65/serverless-plugin/index.js#L244), `stack exe ldd /path/to/executable`. When I run that directly it fails with `.../exe not a dynamic executable`, which... Makes sense.

So yeah, I guess it comes back to the question of why `glibc` isn't getting copied over correctly.

**Comment by koterpillar** [comment]
Please try building with Docker (see #55), when building on that image you'll get the right glibc and won't have to build statically.

However, the ldd error is this plugin's fault, I'll fix that.

**Comment by koterpillar** [comment]
I'm getting these when statically linking:

```
function hsnet_getaddrinfo: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

So you'd still have to build with the right glibc for that.

**Comment by JBetz** [comment]
> Please try building with Docker (see #55), when building on that image you'll get the right glibc and won't have to build statically.

Worked. Took a stupidly long time for docker to download everything it needed, but yeah, it worked.

> So you'd still have to build with the right glibc for that.

Seems there's no getting around that. Annoying, but at least we have a solution.

Thanks for the help. :)

**Comment by koterpillar** [comment]
This is fixed by #57, so the static executables can be now built and uploaded. However, the glibc version caveat still stands.

**Comment by saurabhnanda** [comment]
I upgraded my CI servers from Ubuntu 14.04 to 18.04 and started hitting this error. Why is it not possible to compile and deploy static binaries to AWS Lambda?

**Comment by koterpillar** [comment]
It is possible. To avoid this error, you can either use Docker for building the handlers (recommended) or, if you're sure your glibc matches, turn on the static linking. If you are still seeing issues, please open a new bug with all the information.
