### ISSUE TITLE
Support use in projects with non-Haskell functions

### ISSUE THREAD

**Issue by JBetz** [seek-oss/serverless-haskell#65]
Currently, the plugin tries to build [all functions](https://github.com/seek-oss/serverless-haskell/blob/286b6612fbcd6f67de2e90286608034967b46ef8/serverless-plugin/index.js#L260) as if they were Haskell, and fails if any of them aren't. There should be some way to identify the functions as Haskell so that it only builds them and ignores the others. This would allow it to be used in polyglot projects.

**Comment by JBetz** [comment]
What about something like in the `buildHandlers` function: 
```javascript
this.deployedFunctions()
   .filter(funcName => this.custom.functions === undefined || this.custom.functions.includes(funcName))
   .forEach(funcName => { ... })
```
That would support the existing behavior in addition to letting you whitelist specific handlers to be built as Haskell functions.

**Comment by koterpillar** [comment]
You don't have to have a custom block, and I think it would be more intuitive to keep it that way.

**Comment by JBetz** [comment]
Okay, I'll open a PR where we can discuss implementation specifics.
