### ISSUE TITLE
Example project not compiling

### ISSUE THREAD

**Issue by FranzSkuffka** [seek-oss/serverless-haskell#69]
Hey there - first off: thanks for this nice techology.

Unfortunately I now spent two hours and could not get it to work. I tried cloning the example project and creating one from scratch. I always run into the following error:

```
~/example-project   
❯ sls invoke local -f hello
Serverless: Package version mismatch: NPM: 0.7.5, Stack: 0.6.7. Versions must be in sync to work correctly. Please install matching versions of NPM and Stack packages by either pinning your NPM version to match stack, or adding an extra-dep in your stack.yaml to match the NPM version.
 
  Error --------------------------------------------------
 
  Package version mismatch.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.32.0
```
Note: I am fairly new to haskell development.
I tried
- adding `extra-dep` to `stack.yaml` but the npm package was not found in the registry. Downgrading to an old version of NPM was not straightforward plus I do not get why the version of NPM would be relevant. Is the message maybe referring to NodeJS rather than NPM? 
- Why do I need a realy old version of stack for this to work?
It would be nice if the example project would be working with the latest or modern versions of stack and node.
- I could not find documentation on the error message.
- I have no clue what to sync with what as I could not find configuration pointing to the versions mentioned in the error message.

**Comment by FranzSkuffka** [comment]
Additional info: node-0.7.5 is not a valid node version

**Comment by koterpillar** [comment]
The package in question is `serverless-haskell` itself. The message should probably read:

> Version of NPM package `serverless-haskell` is X.X.X, version of Stack package `serverless-haskell` is Y.Y.Y.

It should be sufficient to add an `extra-dep` to `stack.yaml` like this: `serverless-haskell-0.7.5`.

If you are still getting problems after that, please post your `package.json` and `stack.yaml`.

**Comment by FranzSkuffka** [comment]
Yes! That was it! Thank you :)
But why is it installing an outdated version of `serverless-haskell` per default? Should I create a PR that pins down the versions?

**Comment by koterpillar** [comment]
Stack uses a long-term support version by default, which doesn't have any breaking changes (see https://www.stackage.org/ for more information). NPM doesn't have such a concept, so it installs the latest version, period.

**Comment by FranzSkuffka** [comment]
Thanks. PR? no PR?

**Comment by koterpillar** [comment]
Exactly which versions do you want to pin? We clearly need to lower the confusion for the users, but perhaps the way to go is a README change in the example project? If you have something in mind, please do make a PR and we can talk there.

**Comment by FranzSkuffka** [comment]
Sorry for the late response. I spent some more time in Haskell and working with this. 
Here are the improvements that I think can be done in this package:
- I think the working example should work out of the box. I suggest pinning the version and make a comment on why the version is pinned in the readme.
- The response returned by the example project is not really compliant - I ended up creating the `Response` and `Payload` data types. Then I got something with an actual body in the response. This was particularly confusing as I got an empty response body and a white screen in chrome so I assumed something must be wrong in another place.
- I encountered the following, already existing issue: https://github.com/dherault/serverless-offline/issues/488.
- The example should contain a basic example of how to read data from the request header and body. That will make things more accessible I think.

There are a few more things that I want to do research on:
- apigw - I did not yet understand the concepts of the apigw well yet because I spent most of my time in frontend so far. Do you have a good read on this?
- elm-bridge is currently incompatible with elm 0.19. This package needs updating and I will see if I can support the authors there
- watch mode - serverless offline watch / stack build watch / elm-bridge watch integration that eliminates the overhead to restart the offline server etc. 

From the work done here I would like to derive a fullstack development environment that includes haskell and elm in a very well integrated manner.
