### ISSUE TITLE
Use new lambda capabilities for native haskell runtime

### ISSUE THREAD

**Issue by scooby** [seek-oss/serverless-haskell#80]
I had been thinking about trying to write a wrapper process based on a node extension to address #24 and #26 but that involved a lot of strange chicanery, especially as we'd have a C shim between Node and Haskell, so it'd get gross.

If we can bind to the [new C++ runtime API](https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/) that seems like the easiest and best route to a genuinely native Haskell runtime.

If no one else is working on this, I'm inclined to take a shot at it, especially if it can all be done through ctypes. My inclination is to write a separate package that calls into the API rather than adding to this, unless it winds up needing some of the types already nicely defined here.

Any thoughts?

**Comment by scooby** [comment]
(It looks like the Rust API may even provide an easier FFI.)

**Comment by scooby** [comment]
The [Rust runtime is here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/runtime.rs) and [the C++ here](https://github.com/awslabs/aws-lambda-cpp/blob/master/src/runtime.cpp). I had thought the client was a bit more sophisticated, but it does look like it's just making HTTP calls. If it's possible to just port it directly to Haskell, that'd be ideal. (Until they change things, I guess...)

**Comment by scooby** [comment]
Yup, they have more [detail here](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html#runtimes-custom-build) and [a tutorial](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html) that does it in bash. (Putting this up here for my reference.)

I think it will make sense to make it replace the current handler that's invoked by Javascript.

**Comment by koterpillar** [comment]
Also https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html (bonus: there is an OpenAPI specification, perhaps that can be used for autogenerating code - although last I checked, could only find a 2.0 (Swagger) package).

**Comment by jesuspc** [comment]
I've been working a bit on an AWS runtime for Haskell. I'm linking it here in case you find it relevant https://github.com/jesuspc/aws-lambda-haskell

**Comment by NickSeagull** [comment]
Hey! 😄 We have a fully working runtime [here](https://github.com/theam/aws-lambda-haskell-runtime).

The good part about it is that it allows you to have a single executable, as it will get the handler name and call it dynamically. We are working on a guide to use it, but basically it revolves around having your handlers in separate files and calling them `handler`, then TemplateHaskell generates a `main` that dispatches everything.

The good part about this is that the runtime stays cached in AWS Lambda and makes everything easier to use, specially for newcomers.

I would be very happy to contribute a PR to this plugin to make it use the runtime :)

**Comment by scooby** [comment]
That would be awesome! So glad I procrastinated on working on it!

**Comment by NickSeagull** [comment]
Progress on this: I have created the PR #82 .
The fork deploys Haskell lambdas using the runtime properly, just remember to add the appropriate ARN to your functions in the `serverless.yml` file.

**Comment by koterpillar** [comment]
Closed by #130.
