### ISSUE TITLE
Error while building via docker within a docker container

### ISSUE THREAD

**Issue by saurabhnanda** [seek-oss/serverless-haskell#85]
I'm packaging/deploying a serverless-haskell project via my CI server. The CI server fires up a docker container to run my build scripts, therefore the command `sls deploy` is being run from within a docker container. The original build container is being run with the following command:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock ubuntu:18.04
```

Inside this docker container, it seems that `sls` is doing the following...

```
/usr/bin/docker run -v /usr/local/bin/stack:/tmp/stack sha256:093b06222f1f8b2c25252d43c0e3242e475121ae135dd6d0ccdef5a2cc8c494b /tmp/stack --version
```

...which is failing because `sls` is expecting `/usr/local/bin/stack` to be present in whatever machine is running this command. However, given my setup, the docker volume mount is happening from the underlying host (not the build container), which doesn't have `/usr/local/bin/stack`

Is there any way around this? Can this one step be skipped or does the final build process also need to mount other directories?

**Comment by koterpillar** [comment]
Stack assumes it is running on the Docker host, or at least the directories from where it is running can be mounted (macOS, for example, ensures this). I can see how this is not the case when you mount the Docker socket. I'm assuming running any `stack --docker` command in your setup will also fail.

I see the following options if you want to get this working:

* In the build container, install Stack into a directory you don't mind mounting to the host _under the same name_ and do so. For example, `docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/stack:/tmp/stack ubuntu:18.04` and put the Stack binary in `/tmp/stack/stack`.
* Disable Docker in the plugin options and change the build container image to a matching [fpco/stack-build](https://hub.docker.com/r/fpco/stack-build).
* Disable Docker in the plugin options and make the executable static.
