### ISSUE TITLE
Example project times out

### ISSUE THREAD

**Issue by JDurstberger** [seek-oss/serverless-haskell#96]
Sorry for raising another issue, but I can't really explain what is going on. 

I have used the stack template to create a new project and updated the resolver to `lts-13.19`. 

I can run the function locally without any issues and deploying it worked also fine.
Unfortunately, running the deployed function times out. 

```
{
    "errorMessage": "2019-05-04T15:54:49.122Z 39a8c872-a36b-47d7-b84c-9d4e694b2029 Task timed out after 6.01 seconds"
}
 
  Error --------------------------------------------------
 
  Invoked function failed
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           11.14.0
     Serverless Version:     1.41.1
```

I have played around with the deployed javascript file and it seems like waiting for the server is the culprit.

`const socket = await connection;`

I have put `return { statusCode: 200, body: JSON.stringify('Hello from Lambda!')};` before this line and the lambda finishes fine. If I put it after awaiting the connection it times out. 

Not sure if anyone can reproduce this or knows what I am doing wrong?

**Comment by JDurstberger** [comment]
I was able to fix this by using docker to build the project.
I used a linux based system to build the project but I guess that wasn't enough. 
I hoped to be able to get around using docker but apparently now

**Comment by koterpillar** [comment]
The culprit is usually the version of glibc, the executable won't be able to start if it's linked against a different one. Did you see any CloudWatch messages from your function that failed to start?

**Comment by JDurstberger** [comment]
Sorry I have already deleted function from AWS. 
I can try to reproduce the issue though if you think it is valuable.

**Comment by koterpillar** [comment]
No, just wanted to confirm my suspicions - if you're satisfied you've found the cause then it's fine.
